## *********************************************************
## 
## File autogenerated for the pcl_decimator package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

##**********************************************************
## Software License Agreement (BSD License)
##
##  Copyright (c) 2008, Willow Garage, Inc.
##  All rights reserved.
##
##  Redistribution and use in source and binary forms, with or without
##  modification, are permitted provided that the following conditions
##  are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##   * Neither the name of the Willow Garage nor the names of its
##     contributors may be used to endorse or promote products derived
##     from this software without specific prior written permission.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
##  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
##  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
##  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
##  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
##  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
##  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
##  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
##  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##  POSSIBILITY OF SUCH DAMAGE.
##**********************************************************/

config_description = [{'srcline': 13, 'description': 'The axis on which to perform the multiple passthroughs', 'max': '', 'cconsttype': 'const char * const', 'ctype': 'std::string', 'srcfile': '../cfg/PCLDecimator.cfg', 'name': 'field_name', 'edit_method': '', 'default': 'y', 'level': 1, 'min': '', 'type': 'str'}, {'srcline': 14, 'description': 'The number of total slices to take from the pointcloud.', 'max': 99, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/PCLDecimator.cfg', 'name': 'num_slices', 'edit_method': '', 'default': 5, 'level': 1, 'min': 1, 'type': 'int'}, {'srcline': 15, 'description': 'The width of a cloud slice in meters.', 'max': 100.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/PCLDecimator.cfg', 'name': 'slice_width', 'edit_method': '', 'default': 0.01, 'level': 1, 'min': 0.001, 'type': 'double'}, {'srcline': 16, 'description': 'The measurement at which to place the first slice.', 'max': 100.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/PCLDecimator.cfg', 'name': 'start_threshold', 'edit_method': '', 'default': -1.0, 'level': 1, 'min': -100.0, 'type': 'double'}, {'srcline': 17, 'description': 'The measurement at which to place the final slice.', 'max': 100.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/PCLDecimator.cfg', 'name': 'end_threshold', 'edit_method': '', 'default': 1.0, 'level': 1, 'min': -100.0, 'type': 'double'}]

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

for param in config_description:
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

