//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the pcl_decimator package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __pcl_decimator__PCLDECIMATORCONFIG_H__
#define __pcl_decimator__PCLDECIMATORCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace pcl_decimator
{
  class PCLDecimatorConfigStatics;
  
  class PCLDecimatorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(PCLDecimatorConfig &config, const PCLDecimatorConfig &max, const PCLDecimatorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PCLDecimatorConfig &config1, const PCLDecimatorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PCLDecimatorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PCLDecimatorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PCLDecimatorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PCLDecimatorConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T PCLDecimatorConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (PCLDecimatorConfig::* field);

      virtual void clamp(PCLDecimatorConfig &config, const PCLDecimatorConfig &max, const PCLDecimatorConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PCLDecimatorConfig &config1, const PCLDecimatorConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PCLDecimatorConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PCLDecimatorConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PCLDecimatorConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PCLDecimatorConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 13 "../cfg/PCLDecimator.cfg"
      std::string field_name;
//#line 14 "../cfg/PCLDecimator.cfg"
      int num_slices;
//#line 15 "../cfg/PCLDecimator.cfg"
      double slice_width;
//#line 16 "../cfg/PCLDecimator.cfg"
      double start_threshold;
//#line 17 "../cfg/PCLDecimator.cfg"
      double end_threshold;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PCLDecimatorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PCLDecimatorConfig &__max__ = __getMax__();
      const PCLDecimatorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PCLDecimatorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PCLDecimatorConfig &__getDefault__();
    static const PCLDecimatorConfig &__getMax__();
    static const PCLDecimatorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const PCLDecimatorConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void PCLDecimatorConfig::ParamDescription<std::string>::clamp(PCLDecimatorConfig &config, const PCLDecimatorConfig &max, const PCLDecimatorConfig &min) const
  {
    return;
  }

  class PCLDecimatorConfigStatics
  {
    friend class PCLDecimatorConfig;
    
    PCLDecimatorConfigStatics()
    {
//#line 13 "../cfg/PCLDecimator.cfg"
      __min__.field_name = "";
//#line 13 "../cfg/PCLDecimator.cfg"
      __max__.field_name = "";
//#line 13 "../cfg/PCLDecimator.cfg"
      __default__.field_name = "y";
//#line 13 "../cfg/PCLDecimator.cfg"
      __param_descriptions__.push_back(PCLDecimatorConfig::AbstractParamDescriptionConstPtr(new PCLDecimatorConfig::ParamDescription<std::string>("field_name", "str", 1, "The axis on which to perform the multiple passthroughs", "", &PCLDecimatorConfig::field_name)));
//#line 14 "../cfg/PCLDecimator.cfg"
      __min__.num_slices = 1;
//#line 14 "../cfg/PCLDecimator.cfg"
      __max__.num_slices = 99;
//#line 14 "../cfg/PCLDecimator.cfg"
      __default__.num_slices = 5;
//#line 14 "../cfg/PCLDecimator.cfg"
      __param_descriptions__.push_back(PCLDecimatorConfig::AbstractParamDescriptionConstPtr(new PCLDecimatorConfig::ParamDescription<int>("num_slices", "int", 1, "The number of total slices to take from the pointcloud.", "", &PCLDecimatorConfig::num_slices)));
//#line 15 "../cfg/PCLDecimator.cfg"
      __min__.slice_width = 0.001;
//#line 15 "../cfg/PCLDecimator.cfg"
      __max__.slice_width = 100.0;
//#line 15 "../cfg/PCLDecimator.cfg"
      __default__.slice_width = 0.01;
//#line 15 "../cfg/PCLDecimator.cfg"
      __param_descriptions__.push_back(PCLDecimatorConfig::AbstractParamDescriptionConstPtr(new PCLDecimatorConfig::ParamDescription<double>("slice_width", "double", 1, "The width of a cloud slice in meters.", "", &PCLDecimatorConfig::slice_width)));
//#line 16 "../cfg/PCLDecimator.cfg"
      __min__.start_threshold = -100.0;
//#line 16 "../cfg/PCLDecimator.cfg"
      __max__.start_threshold = 100.0;
//#line 16 "../cfg/PCLDecimator.cfg"
      __default__.start_threshold = -1.0;
//#line 16 "../cfg/PCLDecimator.cfg"
      __param_descriptions__.push_back(PCLDecimatorConfig::AbstractParamDescriptionConstPtr(new PCLDecimatorConfig::ParamDescription<double>("start_threshold", "double", 1, "The measurement at which to place the first slice.", "", &PCLDecimatorConfig::start_threshold)));
//#line 17 "../cfg/PCLDecimator.cfg"
      __min__.end_threshold = -100.0;
//#line 17 "../cfg/PCLDecimator.cfg"
      __max__.end_threshold = 100.0;
//#line 17 "../cfg/PCLDecimator.cfg"
      __default__.end_threshold = 1.0;
//#line 17 "../cfg/PCLDecimator.cfg"
      __param_descriptions__.push_back(PCLDecimatorConfig::AbstractParamDescriptionConstPtr(new PCLDecimatorConfig::ParamDescription<double>("end_threshold", "double", 1, "The measurement at which to place the final slice.", "", &PCLDecimatorConfig::end_threshold)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<PCLDecimatorConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<PCLDecimatorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    PCLDecimatorConfig __max__;
    PCLDecimatorConfig __min__;
    PCLDecimatorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const PCLDecimatorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PCLDecimatorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PCLDecimatorConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const PCLDecimatorConfig &PCLDecimatorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const PCLDecimatorConfig &PCLDecimatorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const PCLDecimatorConfig &PCLDecimatorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<PCLDecimatorConfig::AbstractParamDescriptionConstPtr> &PCLDecimatorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const PCLDecimatorConfigStatics *PCLDecimatorConfig::__get_statics__()
  {
    const static PCLDecimatorConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PCLDecimatorConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PCLDECIMATORRECONFIGURATOR_H__
