/* Auto-generated by genmsg_cpp for file /home/bill/dev/bk-ros/mapping_msgs/msg/CollisionMap.msg */
#ifndef MAPPING_MSGS_MESSAGE_COLLISIONMAP_H
#define MAPPING_MSGS_MESSAGE_COLLISIONMAP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "mapping_msgs/OrientedBoundingBox.h"

namespace mapping_msgs
{
template <class ContainerAllocator>
struct CollisionMap_ {
  typedef CollisionMap_<ContainerAllocator> Type;

  CollisionMap_()
  : header()
  , boxes()
  {
  }

  CollisionMap_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , boxes(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> >::other >  _boxes_type;
  std::vector< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> >::other >  boxes;


  ROS_DEPRECATED uint32_t get_boxes_size() const { return (uint32_t)boxes.size(); }
  ROS_DEPRECATED void set_boxes_size(uint32_t size) { boxes.resize((size_t)size); }
  ROS_DEPRECATED void get_boxes_vec(std::vector< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> >::other > & vec) const { vec = this->boxes; }
  ROS_DEPRECATED void set_boxes_vec(const std::vector< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> >::other > & vec) { this->boxes = vec; }
private:
  static const char* __s_getDataType_() { return "mapping_msgs/CollisionMap"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "18ca54db41ccebbe82f61f9801dede89"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#header for interpreting box positions\n\
Header header\n\
\n\
#boxes for use in collision testing\n\
OrientedBoundingBox[] boxes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mapping_msgs/OrientedBoundingBox\n\
#the center of the box\n\
geometry_msgs/Point32 center\n\
\n\
#the extents of the box, assuming the center is at the point\n\
geometry_msgs/Point32 extents\n\
\n\
#the axis of the box\n\
geometry_msgs/Point32 axis\n\
\n\
#the angle of rotation around the axis\n\
float32 angle\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, boxes);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, boxes);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(boxes);
    return size;
  }

  typedef boost::shared_ptr< ::mapping_msgs::CollisionMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapping_msgs::CollisionMap_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CollisionMap
typedef  ::mapping_msgs::CollisionMap_<std::allocator<void> > CollisionMap;

typedef boost::shared_ptr< ::mapping_msgs::CollisionMap> CollisionMapPtr;
typedef boost::shared_ptr< ::mapping_msgs::CollisionMap const> CollisionMapConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::mapping_msgs::CollisionMap_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::mapping_msgs::CollisionMap_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace mapping_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mapping_msgs::CollisionMap_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mapping_msgs::CollisionMap_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mapping_msgs::CollisionMap_<ContainerAllocator> > {
  static const char* value() 
  {
    return "18ca54db41ccebbe82f61f9801dede89";
  }

  static const char* value(const  ::mapping_msgs::CollisionMap_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x18ca54db41ccebbeULL;
  static const uint64_t static_value2 = 0x82f61f9801dede89ULL;
};

template<class ContainerAllocator>
struct DataType< ::mapping_msgs::CollisionMap_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mapping_msgs/CollisionMap";
  }

  static const char* value(const  ::mapping_msgs::CollisionMap_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mapping_msgs::CollisionMap_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#header for interpreting box positions\n\
Header header\n\
\n\
#boxes for use in collision testing\n\
OrientedBoundingBox[] boxes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mapping_msgs/OrientedBoundingBox\n\
#the center of the box\n\
geometry_msgs/Point32 center\n\
\n\
#the extents of the box, assuming the center is at the point\n\
geometry_msgs/Point32 extents\n\
\n\
#the axis of the box\n\
geometry_msgs/Point32 axis\n\
\n\
#the angle of rotation around the axis\n\
float32 angle\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const  ::mapping_msgs::CollisionMap_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::mapping_msgs::CollisionMap_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::mapping_msgs::CollisionMap_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mapping_msgs::CollisionMap_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.boxes);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CollisionMap_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapping_msgs::CollisionMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::mapping_msgs::CollisionMap_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "boxes[]" << std::endl;
    for (size_t i = 0; i < v.boxes.size(); ++i)
    {
      s << indent << "  boxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mapping_msgs::OrientedBoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.boxes[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // MAPPING_MSGS_MESSAGE_COLLISIONMAP_H

