(cl:defpackage mapping_msgs-msg
  (:use )
  (:export
   "<COLLISIONOBJECTOPERATION>"
   "COLLISIONOBJECTOPERATION"
   "<POLYGONALMAP>"
   "POLYGONALMAP"
   "<COLLISIONMAP>"
   "COLLISIONMAP"
   "<ORIENTEDBOUNDINGBOX>"
   "ORIENTEDBOUNDINGBOX"
   "<ATTACHEDCOLLISIONOBJECT>"
   "ATTACHEDCOLLISIONOBJECT"
   "<COLLISIONOBJECT>"
   "COLLISIONOBJECT"
  ))

