/* Auto-generated by genmsg_cpp for file /home/bill/dev/bk-ros/bk_sbpl_lattice_planner/msg/SBPLLatticePlannerStats.msg */
#ifndef BK_SBPL_LATTICE_PLANNER_MESSAGE_SBPLLATTICEPLANNERSTATS_H
#define BK_SBPL_LATTICE_PLANNER_MESSAGE_SBPLLATTICEPLANNERSTATS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseStamped.h"
#include "geometry_msgs/PoseStamped.h"

namespace bk_sbpl_lattice_planner
{
template <class ContainerAllocator>
struct SBPLLatticePlannerStats_ {
  typedef SBPLLatticePlannerStats_<ContainerAllocator> Type;

  SBPLLatticePlannerStats_()
  : initial_epsilon(0.0)
  , final_epsilon(0.0)
  , plan_to_first_solution(false)
  , allocated_time(0.0)
  , actual_time(0.0)
  , time_to_first_solution(0.0)
  , solution_cost(0.0)
  , path_size(0.0)
  , final_number_of_expands(0)
  , number_of_expands_initial_solution(0)
  , start()
  , goal()
  {
  }

  SBPLLatticePlannerStats_(const ContainerAllocator& _alloc)
  : initial_epsilon(0.0)
  , final_epsilon(0.0)
  , plan_to_first_solution(false)
  , allocated_time(0.0)
  , actual_time(0.0)
  , time_to_first_solution(0.0)
  , solution_cost(0.0)
  , path_size(0.0)
  , final_number_of_expands(0)
  , number_of_expands_initial_solution(0)
  , start(_alloc)
  , goal(_alloc)
  {
  }

  typedef double _initial_epsilon_type;
  double initial_epsilon;

  typedef double _final_epsilon_type;
  double final_epsilon;

  typedef uint8_t _plan_to_first_solution_type;
  uint8_t plan_to_first_solution;

  typedef double _allocated_time_type;
  double allocated_time;

  typedef double _actual_time_type;
  double actual_time;

  typedef double _time_to_first_solution_type;
  double time_to_first_solution;

  typedef double _solution_cost_type;
  double solution_cost;

  typedef double _path_size_type;
  double path_size;

  typedef int64_t _final_number_of_expands_type;
  int64_t final_number_of_expands;

  typedef int64_t _number_of_expands_initial_solution_type;
  int64_t number_of_expands_initial_solution;

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _start_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  start;

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  goal;


private:
  static const char* __s_getDataType_() { return "bk_sbpl_lattice_planner/SBPLLatticePlannerStats"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b1c85b1cec5e7b196cc477ac1440bbf0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#planner stats\n\
float64 initial_epsilon\n\
float64 final_epsilon\n\
bool plan_to_first_solution\n\
float64 allocated_time\n\
float64 actual_time\n\
float64 time_to_first_solution\n\
float64 solution_cost\n\
float64 path_size\n\
int64 final_number_of_expands\n\
int64 number_of_expands_initial_solution\n\
\n\
#problem stats\n\
geometry_msgs/PoseStamped start\n\
geometry_msgs/PoseStamped goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, initial_epsilon);
    ros::serialization::serialize(stream, final_epsilon);
    ros::serialization::serialize(stream, plan_to_first_solution);
    ros::serialization::serialize(stream, allocated_time);
    ros::serialization::serialize(stream, actual_time);
    ros::serialization::serialize(stream, time_to_first_solution);
    ros::serialization::serialize(stream, solution_cost);
    ros::serialization::serialize(stream, path_size);
    ros::serialization::serialize(stream, final_number_of_expands);
    ros::serialization::serialize(stream, number_of_expands_initial_solution);
    ros::serialization::serialize(stream, start);
    ros::serialization::serialize(stream, goal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, initial_epsilon);
    ros::serialization::deserialize(stream, final_epsilon);
    ros::serialization::deserialize(stream, plan_to_first_solution);
    ros::serialization::deserialize(stream, allocated_time);
    ros::serialization::deserialize(stream, actual_time);
    ros::serialization::deserialize(stream, time_to_first_solution);
    ros::serialization::deserialize(stream, solution_cost);
    ros::serialization::deserialize(stream, path_size);
    ros::serialization::deserialize(stream, final_number_of_expands);
    ros::serialization::deserialize(stream, number_of_expands_initial_solution);
    ros::serialization::deserialize(stream, start);
    ros::serialization::deserialize(stream, goal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(initial_epsilon);
    size += ros::serialization::serializationLength(final_epsilon);
    size += ros::serialization::serializationLength(plan_to_first_solution);
    size += ros::serialization::serializationLength(allocated_time);
    size += ros::serialization::serializationLength(actual_time);
    size += ros::serialization::serializationLength(time_to_first_solution);
    size += ros::serialization::serializationLength(solution_cost);
    size += ros::serialization::serializationLength(path_size);
    size += ros::serialization::serializationLength(final_number_of_expands);
    size += ros::serialization::serializationLength(number_of_expands_initial_solution);
    size += ros::serialization::serializationLength(start);
    size += ros::serialization::serializationLength(goal);
    return size;
  }

  typedef boost::shared_ptr< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SBPLLatticePlannerStats
typedef  ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<std::allocator<void> > SBPLLatticePlannerStats;

typedef boost::shared_ptr< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats> SBPLLatticePlannerStatsPtr;
typedef boost::shared_ptr< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats const> SBPLLatticePlannerStatsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace bk_sbpl_lattice_planner

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b1c85b1cec5e7b196cc477ac1440bbf0";
  }

  static const char* value(const  ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb1c85b1cec5e7b19ULL;
  static const uint64_t static_value2 = 0x6cc477ac1440bbf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bk_sbpl_lattice_planner/SBPLLatticePlannerStats";
  }

  static const char* value(const  ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#planner stats\n\
float64 initial_epsilon\n\
float64 final_epsilon\n\
bool plan_to_first_solution\n\
float64 allocated_time\n\
float64 actual_time\n\
float64 time_to_first_solution\n\
float64 solution_cost\n\
float64 path_size\n\
int64 final_number_of_expands\n\
int64 number_of_expands_initial_solution\n\
\n\
#problem stats\n\
geometry_msgs/PoseStamped start\n\
geometry_msgs/PoseStamped goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.initial_epsilon);
    stream.next(m.final_epsilon);
    stream.next(m.plan_to_first_solution);
    stream.next(m.allocated_time);
    stream.next(m.actual_time);
    stream.next(m.time_to_first_solution);
    stream.next(m.solution_cost);
    stream.next(m.path_size);
    stream.next(m.final_number_of_expands);
    stream.next(m.number_of_expands_initial_solution);
    stream.next(m.start);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SBPLLatticePlannerStats_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::bk_sbpl_lattice_planner::SBPLLatticePlannerStats_<ContainerAllocator> & v) 
  {
    s << indent << "initial_epsilon: ";
    Printer<double>::stream(s, indent + "  ", v.initial_epsilon);
    s << indent << "final_epsilon: ";
    Printer<double>::stream(s, indent + "  ", v.final_epsilon);
    s << indent << "plan_to_first_solution: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_to_first_solution);
    s << indent << "allocated_time: ";
    Printer<double>::stream(s, indent + "  ", v.allocated_time);
    s << indent << "actual_time: ";
    Printer<double>::stream(s, indent + "  ", v.actual_time);
    s << indent << "time_to_first_solution: ";
    Printer<double>::stream(s, indent + "  ", v.time_to_first_solution);
    s << indent << "solution_cost: ";
    Printer<double>::stream(s, indent + "  ", v.solution_cost);
    s << indent << "path_size: ";
    Printer<double>::stream(s, indent + "  ", v.path_size);
    s << indent << "final_number_of_expands: ";
    Printer<int64_t>::stream(s, indent + "  ", v.final_number_of_expands);
    s << indent << "number_of_expands_initial_solution: ";
    Printer<int64_t>::stream(s, indent + "  ", v.number_of_expands_initial_solution);
    s << indent << "start: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BK_SBPL_LATTICE_PLANNER_MESSAGE_SBPLLATTICEPLANNERSTATS_H

